### ISSUE TITLE
Improve how the Names of months are show

### ISSUE THREAD

**Issue by davidcostadev** [withmoney/withmoney-mobile#48]
In mobile devices, the names of months are not shown correctly, maybe just show the first three letters os word

AGO  SET OUT 

to show better

**Comment by capaci** [comment]
@davidcostadev can I create a PR to solve this?
I'd change the string format from `'MMMM YY'` to `'MMM YY'`

**Comment by davidcostadev** [comment]
Yes, you can. I love the idea.
